name: CI

on:
  push:
    branches:
      - main

jobs:
  validate_vm:
    name: Validate VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validation
        run: |
          echo "validation..."
          ./terraform/script_init.sh
          terraform -chdir="./terraform" --version
          terraform -chdir="./terraform" plan -var "esxi_password=$TF_VAR_esxi_password" -var "esxi_username=$TF_VAR_esxi_username"
        tags:
          - lab20

  terrafom_fmt:
    name: Format Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Formatation
        run: |
          echo "formatation..."
          ./terraform/script_init.sh
          terraform -chdir="./terraform" fmt
        

  create_vm:
    name: Create VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialization
        run: |
          echo "Initialization..."
          ./terraform/script_init.sh
          terraform -chdir="./terraform" --version
          terraform -chdir="./terraform" apply -var "esxi_password=''" -var "esxi_username=''" --auto-approve
        

  playbook_ansible:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute playbook
        run: |
          echo "execution playbook..."
          ansible-playbook -i inventory.ini --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ansible/playbook.yml
        

  curl_command:
    name: Curl Command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Curl
        run: |
          echo "curl 10.10.10.200..."
          curl http://10.10.10.200:8080
        

  destroy_vm:
    name: Destroy VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: VM Destruction
        run: |
          echo "VM it's to be destroyed..."
          ./terraform/script_init.sh
          terraform -chdir="./terraform" --version
          terraform -chdir="./terraform" destroy -var "esxi_password=$TF_VAR_esxi_password" -var "esxi_username=$TF_VAR_esxi_username" --auto-approve
     
